<a href="https://colab.research.google.com/github/vinifred29/mashiya-s-LU-datascience-assignments/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar= np.arange(2,53,3)
ar

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [ ]:
A=[1,2,4,9,0]
A1=[66,456,2,355,98]
arr1=np.array(A)
arr2=np.array(A1)
print(arr1)
print(arr2)
a=np.concatenate((arr1,arr2))
print(a)
b=np.sort(a)
print(b)

[1 2 4 9 0]
[ 66 456   2 355  98]
[  1   2   4   9   0  66 456   2 355  98]
[  0   1   2   2   4   9  66  98 355 456]


In [ ]:
b=np.ndarray([4,6,2]) 
print(b)

c=np.ndim(b)
print(c)


v=np.size(b)
print(v)

[[[2.60036315e-316 2.50626933e-316]
  [2.50617684e-316 2.50629067e-316]
  [2.50620530e-316 2.50624799e-316]
  [0.00000000e+000 2.50634048e-316]
  [2.50623376e-316 0.00000000e+000]
  [2.54373295e-316 2.50619107e-316]]

 [[2.50633336e-316 2.50634759e-316]
  [2.50625510e-316 2.50635471e-316]
  [2.54375429e-316 2.50614838e-316]
  [2.54377326e-316 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[2.54376615e-316 2.50641162e-316]
  [2.50626222e-316 0.00000000e+000]
  [0.00000000e+000 2.50639739e-316]
  [0.00000000e+000 2.50615550e-316]
  [2.50621953e-316 2.54374006e-316]
  [2.50629779e-316 2.54374717e-316]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [2.50619819e-316 3.18899217e-316]
  [0.00000000e+000 0.00000000e+000]
  [2.50632625e-316 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]
3
48


In [ ]:
ar.shape

(17,)

In [ ]:
r= ar[np.newaxis, :]
r.shape

(1, 17)

In [ ]:
r

array([[ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47,
        50]])

In [ ]:
c= ar[:, np.newaxis]
print(c.shape)

c

(17, 1)


array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17],
       [20],
       [23],
       [26],
       [29],
       [32],
       [35],
       [38],
       [41],
       [44],
       [47],
       [50]])

In [ ]:
print(ar)

print(np.ndim(ar))

ar2 = np.expand_dims(ar, axis=(1,-2,3))
print(ar2.shape)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
1
(17, 1, 1, 1)
